import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, MapPin, Plus, Trash2 } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { ApiError } from '../servicos/api';
import { adminConfiguracaoService } from '../servicos/adminConfiguracaoService';
import { calendarioService, type DadosAgenda, type DiaDaSemana } from '../servicos/calendarioService';

const dias:Record<DiaDaSemana,string>={MONDAY:'Segunda-feira',TUESDAY:'Terça-feira',WEDNESDAY:'Quarta-feira',THURSDAY:'Quinta-feira',FRIDAY:'Sexta-feira',SATURDAY:'Sábado',SUNDAY:'Domingo'};
const etapas=['Escopo','Período','Horários','Revisão'];
const hoje=new Date().toISOString().slice(0,10);
const data=(valor:string)=>new Date(`${valor}T12:00`).toLocaleDateString('pt-BR');

export function AdminNovaAgendaPage(){
 const navigate=useNavigate(),queryClient=useQueryClient();
 const [etapa,setEtapa]=useState(1),[form,setForm]=useState<DadosAgenda>({nome:'',localId:'',modalidadeId:'',inicio:hoje,fim:`${new Date().getFullYear()+1}-12-31`,regras:[]});
 const locais=useQuery({queryKey:['configuracoes','locais'],queryFn:adminConfiguracaoService.listarLocais});
 const modalidades=useQuery({queryKey:['configuracoes','modalidades'],queryFn:adminConfiguracaoService.listarModalidades});
 const categorias=useQuery({queryKey:['configuracoes','categorias'],queryFn:adminConfiguracaoService.listarCategorias});
 const criacao=useMutation({mutationFn:calendarioService.criarAgenda,onSuccess:async()=>{await queryClient.invalidateQueries({queryKey:['configuracoes','calendario']});navigate('/admin/configuracoes/calendario',{replace:true})},onError:()=>window.scrollTo({top:0,behavior:'smooth'})});
 const total=useMemo(()=>form.regras.reduce((n,r)=>n+r.horarios.length,0),[form.regras]);
 const local=locais.data?.find(i=>i.id===form.localId)?.nome,modalidade=modalidades.data?.find(i=>i.id===form.modalidadeId)?.nome,categoria=categorias.data?.find(i=>i.id===form.categoriaId)?.nome;
 const carregando=locais.isPending||modalidades.isPending||categorias.isPending,falha=locais.error??modalidades.error??categorias.error;
 const etapaValida=etapa===1?Boolean(form.nome.trim()&&form.localId&&form.modalidadeId):etapa===2?Boolean(form.inicio&&form.fim&&form.fim>=form.inicio):etapa===3?Boolean(total):true;
 function alternar(d:DiaDaSemana){setForm(a=>({...a,regras:a.regras.some(r=>r.diaDaSemana===d)?a.regras.filter(r=>r.diaDaSemana!==d):[...a.regras,{diaDaSemana:d,horarios:['19:00']}]}))}
 function horario(d:DiaDaSemana,i:number,v:string){setForm(a=>({...a,regras:a.regras.map(r=>r.diaDaSemana===d?{...r,horarios:r.horarios.map((h,j)=>j===i?v:h)}:r)}))}
 function adicionar(d:DiaDaSemana){setForm(a=>({...a,regras:a.regras.map(r=>r.diaDaSemana===d?{...r,horarios:[...r.horarios,'20:00']}:r)}))}
 function remover(d:DiaDaSemana,i:number){setForm(a=>({...a,regras:a.regras.map(r=>r.diaDaSemana===d?{...r,horarios:r.horarios.filter((_,j)=>i!==j)}:r).filter(r=>r.horarios.length)}))}
 function submeter(e:FormEvent){e.preventDefault();if(etapa===4)criacao.mutate(form);else if(etapaValida)setEtapa(n=>n+1)}
 return <section className="admin-create-match admin-agenda-wizard" aria-labelledby="titulo-nova-agenda">
  <header className="admin-create-heading"><div><button type="button" aria-label="Voltar para agendas" onClick={()=>navigate('/admin/configuracoes/calendario')}><ArrowLeft/></button><div><h1 id="titulo-nova-agenda">Nova agenda</h1><p>Etapa {etapa} de 4 · {etapas[etapa-1]}</p></div></div><button type="button" className="admin-button admin-button-secondary" onClick={()=>navigate('/admin/configuracoes/calendario')}>Cancelar</button></header>
  <nav className="admin-wizard-steps" aria-label="Etapas da nova agenda">{etapas.map((nome,i)=>{const numero=i+1,concluida=numero<etapa,ativa=numero===etapa;return <button type="button" key={nome} className={`${ativa?'active ':''}${concluida?'complete':''}`} disabled={numero>etapa} onClick={()=>numero<etapa&&setEtapa(numero)}><span>{concluida?<Check/>:numero}</span><b>{nome}</b></button>})}</nav>
  {criacao.isError&&<div className="admin-inline-error admin-create-error" role="alert"><span>{criacao.error instanceof ApiError?criacao.error.detail:'Não foi possível criar a agenda.'}</span></div>}
  {carregando&&<div className="admin-table-skeleton"><span/><span/><span/></div>}{falha&&<div className="admin-inline-error"><span>Não foi possível carregar os dados necessários.</span><button onClick={()=>{void locais.refetch();void modalidades.refetch();void categorias.refetch()}}>Tentar novamente</button></div>}
  {!carregando&&!falha&&<form id="form-nova-agenda" onSubmit={submeter}>
   {etapa===1&&<section className="admin-form-card admin-wizard-card"><header><h2>Onde as partidas acontecerão?</h2><p>Dê um nome à agenda e escolha seu local, modalidade e público.</p></header><div className="admin-form-fields admin-form-fields-two"><label className="admin-form-field-full">Nome da agenda<input autoFocus required maxLength={120} value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} placeholder="Ex.: Futebol no Campo Principal — 2027"/></label><label>Local<select required value={form.localId} onChange={e=>setForm({...form,localId:e.target.value})}><option value="">Selecione um local</option>{locais.data?.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></label><label>Modalidade<select required value={form.modalidadeId} onChange={e=>setForm({...form,modalidadeId:e.target.value,categoriaId:undefined})}><option value="">Selecione uma modalidade</option>{modalidades.data?.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></label><label className="admin-form-field-full">Categoria <span>Opcional</span><select disabled={!form.modalidadeId} value={form.categoriaId??''} onChange={e=>setForm({...form,categoriaId:e.target.value?Number(e.target.value):undefined})}><option value="">Todas as categorias</option>{categorias.data?.map(i=><option key={i.id} value={i.id}>{i.nome}</option>)}</select></label></div></section>}
   {etapa===2&&<section className="admin-form-card admin-wizard-card"><header><h2>Por quanto tempo esta agenda será válida?</h2><p>O período pode atravessar anos. As duas datas estão incluídas.</p></header><div className="admin-form-fields admin-form-fields-two"><label>Data inicial<input autoFocus type="date" required max={form.fim} value={form.inicio} onChange={e=>setForm({...form,inicio:e.target.value})}/></label><label>Data final<input type="date" required min={form.inicio} value={form.fim} onChange={e=>setForm({...form,fim:e.target.value})}/></label>{form.inicio&&form.fim<form.inicio&&<p className="admin-form-error admin-form-field-full">A data final deve ser igual ou posterior à inicial.</p>}<div className="admin-wizard-period-preview admin-form-field-full"><CalendarDays/><span><b>{data(form.inicio)}</b> até <b>{data(form.fim)}</b></span></div></div></section>}
   {etapa===3&&<section className="admin-form-card admin-wizard-card"><header><h2>Em quais dias e horários haverá partidas?</h2><p>Ative somente os dias utilizados e adicione os horários de início.</p></header><div className="admin-agenda-week admin-agenda-week-page">{(Object.entries(dias) as [DiaDaSemana,string][]).map(([d,nome])=>{const regra=form.regras.find(r=>r.diaDaSemana===d);return <section key={d} className={regra?'selected':''}><header><b>{nome}</b><button type="button" onClick={()=>regra?adicionar(d):alternar(d)}><Plus/>{regra?'Adicionar':'Ativar dia'}</button></header>{regra?<div>{regra.horarios.map((h,i)=><span key={`${d}-${i}`}><input type="time" required value={h.slice(0,5)} onChange={e=>horario(d,i,e.target.value)}/><button type="button" onClick={()=>remover(d,i)} aria-label={`Remover horário de ${nome}`}><Trash2/></button></span>)}</div>:<small>Sem horários</small>}</section>})}</div>{!total&&<p className="admin-wizard-hint">Ative pelo menos um dia para continuar.</p>}</section>}
   {etapa===4&&<section className="admin-form-card admin-wizard-card"><header><h2>Revise antes de criar</h2><p>Confirme os dados ou volte à etapa que deseja corrigir.</p></header><div className="admin-wizard-review"><article><span><MapPin/></span><div><small>Agenda e local</small><strong>{form.nome}</strong><p>{local}</p></div><button type="button" onClick={()=>setEtapa(1)}>Editar</button></article><article><span><CalendarDays/></span><div><small>Modalidade e categoria</small><strong>{modalidade}</strong><p>{categoria??'Todas as categorias'}</p></div><button type="button" onClick={()=>setEtapa(1)}>Editar</button></article><article><span><CalendarDays/></span><div><small>Período</small><strong>{data(form.inicio)} até {data(form.fim)}</strong><p>Datas inicial e final inclusas</p></div><button type="button" onClick={()=>setEtapa(2)}>Editar</button></article><article><span><Clock3/></span><div><small>Grade semanal</small><strong>{total} {total===1?'horário':'horários'} em {form.regras.length} {form.regras.length===1?'dia':'dias'}</strong><p>{form.regras.map(r=>`${dias[r.diaDaSemana]}: ${r.horarios.map(h=>h.slice(0,5)).join(', ')}`).join(' · ')}</p></div><button type="button" onClick={()=>setEtapa(3)}>Editar</button></article></div></section>}
   <footer className="admin-wizard-actions"><button type="button" className="admin-button admin-button-secondary" onClick={()=>etapa===1?navigate('/admin/configuracoes/calendario'):setEtapa(n=>n-1)}><ArrowLeft/>{etapa===1?'Cancelar':'Voltar'}</button><button type="submit" className="admin-button admin-button-primary" disabled={!etapaValida||criacao.isPending}>{etapa===4?(criacao.isPending?'Criando…':'Criar agenda'):'Continuar'}{etapa<4&&<ArrowRight/>}</button></footer>
  </form>}
 </section>
}
