import { Pencil, Plus } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';

import { ApiError } from '../servicos/api';
import { calendarioService, type DiaFuncionamento, type ExcecaoCalendario } from '../servicos/calendarioService';
import { AvisoTemporario } from '../componentes/ui/AvisoTemporario';
import { Confirmacao } from '../componentes/ui/Confirmacao';
import { Sheet } from '../componentes/ui/Sheet';

const dias: Record<DiaFuncionamento['diaDaSemana'], string> = { MONDAY: 'Segunda-feira', TUESDAY: 'Terça-feira', WEDNESDAY: 'Quarta-feira', THURSDAY: 'Quinta-feira', FRIDAY: 'Sexta-feira', SATURDAY: 'Sábado', SUNDAY: 'Domingo' };
const tipos: Record<ExcecaoCalendario['tipo'], string> = { FERIADO: 'Feriado', RECESSO: 'Recesso', BLOQUEIO: 'Bloqueio' };
const data = new Intl.DateTimeFormat('pt-BR');

export function AdminCalendarioPage() {
  const [aviso, setAviso] = useState('');
  const [diaAberto, setDiaAberto] = useState(false);
  const [diaEmEdicao, setDiaEmEdicao] = useState<DiaFuncionamento | null>(null);
  const [diaDaSemana, setDiaDaSemana] = useState<DiaFuncionamento['diaDaSemana']>('MONDAY');
  const [horario, setHorario] = useState('19:00');
  const [excecaoAberta, setExcecaoAberta] = useState(false);
  const [excecaoEmEdicao, setExcecaoEmEdicao] = useState<ExcecaoCalendario | null>(null);
  const [descricao, setDescricao] = useState('');
  const [tipoExcecao, setTipoExcecao] = useState<ExcecaoCalendario['tipo']>('FERIADO');
  const [inicio, setInicio] = useState('');
  const [fim, setFim] = useState('');

  const funcionamento = useQuery({ queryKey: ['configuracoes', 'calendario', 'dias'], queryFn: calendarioService.listarDias });
  const excecoes = useQuery({ queryKey: ['configuracoes', 'calendario', 'excecoes'], queryFn: calendarioService.listarExcecoes });
  const salvarDia = useMutation({ mutationFn: () => diaEmEdicao ? calendarioService.editarDia(diaEmEdicao.id, diaDaSemana, horario) : calendarioService.criarDia(diaDaSemana, horario), onSuccess: () => { setDiaAberto(false); setDiaEmEdicao(null); setAviso(`Horário ${diaEmEdicao ? 'atualizado' : 'cadastrado'} com sucesso.`); void funcionamento.refetch(); } });
  const excluirDia = useMutation({ mutationFn: () => calendarioService.excluirDia(diaEmEdicao!.id), onSuccess: () => { setDiaAberto(false); setDiaEmEdicao(null); setAviso('Horário removido com sucesso.'); void funcionamento.refetch(); } });
  const salvarExcecao = useMutation({ mutationFn: () => { const dados = { descricao: descricao.trim(), tipo: tipoExcecao, inicio, fim }; return excecaoEmEdicao ? calendarioService.editarExcecao(excecaoEmEdicao.id, dados) : calendarioService.criarExcecao(dados); }, onSuccess: () => { setExcecaoAberta(false); setExcecaoEmEdicao(null); setAviso(`Período ${excecaoEmEdicao ? 'atualizado' : 'cadastrado'} com sucesso.`); void excecoes.refetch(); } });
  const excluirExcecao = useMutation({ mutationFn: () => calendarioService.excluirExcecao(excecaoEmEdicao!.id), onSuccess: () => { setExcecaoAberta(false); setExcecaoEmEdicao(null); setAviso('Período removido com sucesso.'); void excecoes.refetch(); } });
  const intervaloInvalido = Boolean(inicio && fim && inicio > fim);
  const falhou = funcionamento.isError || excecoes.isError;

  function novoDia() { setDiaEmEdicao(null); setDiaDaSemana('MONDAY'); setHorario('19:00'); salvarDia.reset(); excluirDia.reset(); setDiaAberto(true); }
  function editarDia(item: DiaFuncionamento) { setDiaEmEdicao(item); setDiaDaSemana(item.diaDaSemana); setHorario(item.horario.slice(0, 5)); salvarDia.reset(); excluirDia.reset(); setDiaAberto(true); }
  function novaExcecao() { setExcecaoEmEdicao(null); setDescricao(''); setTipoExcecao('FERIADO'); setInicio(''); setFim(''); salvarExcecao.reset(); excluirExcecao.reset(); setExcecaoAberta(true); }
  function editarExcecao(item: ExcecaoCalendario) { setExcecaoEmEdicao(item); setDescricao(item.descricao); setTipoExcecao(item.tipo); setInicio(item.inicio); setFim(item.fim); salvarExcecao.reset(); excluirExcecao.reset(); setExcecaoAberta(true); }
  const erro = (falha: Error, padrao: string) => falha instanceof ApiError ? falha.detail : padrao;

  return <section className="admin-card admin-users-page" aria-labelledby="titulo-calendario">
    <header className="admin-card-header"><div><h1 id="titulo-calendario">Calendário</h1><p>Gerencie o funcionamento do clube, feriados, recessos e bloqueios.</p></div><button type="button" className="admin-button admin-button-secondary" onClick={() => { void funcionamento.refetch(); void excecoes.refetch(); }}>Atualizar</button></header>
    {falhou && <div className="admin-inline-error" role="alert"><span>Não foi possível carregar o calendário.</span><button onClick={() => { void funcionamento.refetch(); void excecoes.refetch(); }}>Tentar novamente</button></div>}
    <div className="admin-calendar-grid">
      <article className="admin-users-panel"><header className="admin-config-section-header"><div><h2>Horários de funcionamento</h2><p>Dias e horários disponíveis para partidas.</p></div><button type="button" className="admin-button admin-button-primary" onClick={novoDia}><Plus aria-hidden="true" />Adicionar</button></header>{funcionamento.isPending && <div className="admin-table-skeleton"><span /><span /><span /></div>}{funcionamento.isSuccess && funcionamento.data.length === 0 && <div className="admin-empty-state"><h3>Nenhum horário configurado</h3><p>Cadastre os horários regulares do clube.</p></div>}{funcionamento.data?.map((item) => <div className="admin-config-row" key={item.id}><div><strong>{dias[item.diaDaSemana]}</strong><small>{item.horario.slice(0, 5)}</small></div><button className="ui-icon-button" type="button" aria-label={`Editar ${dias[item.diaDaSemana]} às ${item.horario.slice(0, 5)}`} onClick={() => editarDia(item)}><Pencil aria-hidden="true" /></button></div>)}</article>
      <article className="admin-users-panel"><header className="admin-config-section-header"><div><h2>Feriados, recessos e bloqueios</h2><p>Períodos em que novas partidas não podem ser criadas.</p></div><button type="button" className="admin-button admin-button-primary" onClick={novaExcecao}><Plus aria-hidden="true" />Adicionar</button></header>{excecoes.isPending && <div className="admin-table-skeleton"><span /><span /><span /></div>}{excecoes.isSuccess && excecoes.data.length === 0 && <div className="admin-empty-state"><h3>Nenhum período cadastrado</h3><p>Feriados, recessos e bloqueios aparecerão aqui.</p></div>}{excecoes.data?.map((item) => <div className="admin-config-row" key={item.id}><div><strong>{item.descricao}</strong><small>{data.format(new Date(`${item.inicio}T12:00:00`))} até {data.format(new Date(`${item.fim}T12:00:00`))}</small></div><span className="admin-badge admin-badge-rascunho">{tipos[item.tipo]}</span><button className="ui-icon-button" type="button" aria-label={`Editar ${item.descricao}`} onClick={() => editarExcecao(item)}><Pencil aria-hidden="true" /></button></div>)}</article>
    </div>
    <Sheet aberto={diaAberto} aoAlterar={setDiaAberto} titulo={diaEmEdicao ? 'Editar horário' : 'Adicionar horário'} descricao="Defina um horário recorrente para realização de partidas."><form className="admin-sheet-section admin-sheet-form" onSubmit={(e: FormEvent) => { e.preventDefault(); salvarDia.mutate(); }}><label>Dia da semana<select value={diaDaSemana} onChange={(e) => setDiaDaSemana(e.target.value as DiaFuncionamento['diaDaSemana'])}>{Object.entries(dias).map(([valor, rotulo]) => <option value={valor} key={valor}>{rotulo}</option>)}</select></label><label>Horário<input type="time" required value={horario} onChange={(e) => setHorario(e.target.value)} /></label>{salvarDia.isError && <p className="admin-sheet-error" role="alert">{erro(salvarDia.error, 'Não foi possível salvar o horário.')}</p>}<div className="admin-sheet-actions"><button type="button" className="admin-button admin-button-secondary" onClick={() => setDiaAberto(false)}>Cancelar</button><button className="admin-button admin-button-primary" disabled={salvarDia.isPending || !horario}>{salvarDia.isPending ? 'Salvando…' : 'Salvar'}</button></div></form>{diaEmEdicao && <div className="admin-danger-zone"><h3>Remover horário</h3><p>Novas partidas não poderão mais ser criadas nesse dia e horário.</p><Confirmacao acionador={<button className="admin-button admin-button-danger">Remover horário</button>} titulo="Remover horário de funcionamento?" descricao="Partidas existentes serão preservadas, mas o horário deixará de ser oferecido para novos agendamentos." rotuloConfirmacao="Remover horário" processando={excluirDia.isPending} aoConfirmar={() => excluirDia.mutate()} />{excluirDia.isError && <p className="admin-sheet-error">{erro(excluirDia.error, 'Não foi possível remover o horário.')}</p>}</div>}</Sheet>
    <Sheet aberto={excecaoAberta} aoAlterar={setExcecaoAberta} titulo={excecaoEmEdicao ? 'Editar período' : 'Adicionar período'} descricao="Bloqueie uma data ou intervalo para novos agendamentos."><form className="admin-sheet-section admin-sheet-form" onSubmit={(e: FormEvent) => { e.preventDefault(); if (!intervaloInvalido) salvarExcecao.mutate(); }}><label>Descrição<input required maxLength={150} value={descricao} onChange={(e) => setDescricao(e.target.value)} placeholder="Ex.: Recesso de fim de ano" /></label><label>Tipo<select value={tipoExcecao} onChange={(e) => setTipoExcecao(e.target.value as ExcecaoCalendario['tipo'])}>{Object.entries(tipos).map(([valor, rotulo]) => <option value={valor} key={valor}>{rotulo}</option>)}</select></label><label>Data inicial<input type="date" required max={fim || undefined} value={inicio} onChange={(e) => setInicio(e.target.value)} /></label><label>Data final<input type="date" required min={inicio || undefined} value={fim} onChange={(e) => setFim(e.target.value)} aria-invalid={intervaloInvalido} /></label>{intervaloInvalido && <p className="admin-date-error" role="alert">A data final deve ser igual ou posterior à inicial.</p>}{salvarExcecao.isError && <p className="admin-sheet-error" role="alert">{erro(salvarExcecao.error, 'Não foi possível salvar o período.')}</p>}<div className="admin-sheet-actions"><button type="button" className="admin-button admin-button-secondary" onClick={() => setExcecaoAberta(false)}>Cancelar</button><button className="admin-button admin-button-primary" disabled={salvarExcecao.isPending || !descricao.trim() || !inicio || !fim || intervaloInvalido}>{salvarExcecao.isPending ? 'Salvando…' : 'Salvar'}</button></div></form>{excecaoEmEdicao && <div className="admin-danger-zone"><h3>Excluir período</h3><p>O período será removido e as datas voltarão a aceitar novos agendamentos.</p><Confirmacao acionador={<button className="admin-button admin-button-danger">Excluir período</button>} titulo="Excluir período do calendário?" descricao={`O período ${excecaoEmEdicao.descricao} será removido. Esta ação não pode ser desfeita.`} rotuloConfirmacao="Excluir período" processando={excluirExcecao.isPending} aoConfirmar={() => excluirExcecao.mutate()} />{excluirExcecao.isError && <p className="admin-sheet-error">{erro(excluirExcecao.error, 'Não foi possível excluir o período.')}</p>}</div>}</Sheet>
    {aviso && <AvisoTemporario mensagem={aviso} aoFechar={() => setAviso('')} />}
  </section>;
}
